version: '3.9'

services:
  postgres:
    image: postgres:17.5
    container_name: robo-postgres
    stop_signal: SIGKILL
    env_file:
      - '.env'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

#  server:
#    build:
#      context: ./src
#      dockerfile: Dockerfile
#    container_name: robo-server
#    stop_signal: SIGKILL
#    env_file:
#      - '.env'
#    ports:
#      - '8000:8000'
#    depends_on:
#      - postgres
