# Generated by Django 4.2 on 2024-07-20 12:20

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=shopapp.models.path_to_category_img)),
                ('subcategories', models.ManyToManyField(to='shopapp.category')),
            ],
        ),
    ]
