# Generated by Django 4.2 on 2024-07-21 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('freeDelivery', models.BooleanField(default=False)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.category')),
                ('tags', models.ManyToManyField(related_name='products', to='shopapp.tag')),
            ],
        ),
    ]
