# Generated by Django 4.2 on 2024-07-30 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('fullDescription', models.TextField(blank=True, max_length=500, null=True)),
                ('freeDelivery', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('limited', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shopapp.category')),
                ('tags', models.ManyToManyField(related_name='products', to='shopapp.tag')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
