# Generated by Django 4.2 on 2024-07-24 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_specification_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('deliveryType', models.CharField(choices=[('Del', 'Доставка'), ('ExDel', 'Экспресс-доставка')], max_length=50)),
                ('paymentType', models.CharField(choices=[('Online', 'Онлайн картой'), ('Alien Online', 'Онлайн со случайного чужого счёта')], max_length=50)),
                ('totalCost', models.FloatField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(related_name='orders', to='shopapp.product')),
            ],
        ),
    ]
