# Generated by Django 4.2 on 2024-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('deliveryType', models.CharField(choices=[('ordinary', 'free'), ('express', 'paying')], max_length=99)),
                ('paymentType', models.CharField(choices=[('online', 'card'), ('someone', 'cash')], max_length=99)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(related_name='orders', to='shopapp.product')),
            ],
        ),
    ]
