# Generated by Django 4.2 on 2024-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=50)),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
