# Generated by Django 4.2 on 2024-07-30 08:32

from django.db import migrations, models
import django.db.models.deletion
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shopapp.models.path_to_img)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopapp.sale')),
            ],
        ),
    ]
