# Generated by Django 4.2 on 2024-07-23 10:36

import django.core.validators
from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('name', models.CharField(max_length=50)),
                ('month', models.PositiveSmallIntegerField(validators=[myauth.models.payment_month_validator])),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2027)])),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
            ],
        ),
    ]
